dist: trusty
sudo: false

language: php
php:
  - '7.1'

install:
  - composer install

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs -n -p --encoding=utf-8 --standard=PSR2 --extensions=php ./src/ ./tests/
